services:
  - type: web
    name: stanford-prison-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn standfordPrison:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0

  - type: web
    name: stanford-prison-frontend
    runtime: static
    buildCommand: cd stanford-prison && npm install && npm run build
    staticPublishPath: ./stanford-prison/dist
    envVars:
      - key: VITE_API_URL
        value: https://stanford-prison-api.onrender.com